name: Build and upload to PyPI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build release
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: pip install wheel setuptools tensorflow==2.8.0

      - name: Build wheel
        run: python setup.py sdist bdist_wheel

      - name: Upload Python wheel
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/*
          if-no-files-found: error
    
  upload_pypi:
    needs: build_wheels
    runs-on: ubuntu-20.04
    
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      
      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.gradient_accumulator_deploy_token }}
