name: Test self-hosted

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Create environment and install python packages
        run: |
          cd ${{github.workspace}}
          mkdir tmp
          cd tmp
          python3 -m virtualenv -p python3 venv --clear
          source venv/bin/activate
          python3 -m pip install wheel setuptools
          python3 -m pip install tensorflow-metal

      - name: Build wheel
        run: python3 setup.py bdist_wheel

      - name: Upload Python wheel
        uses: actions/upload-artifact@v3
        with:
          name: Python wheel
          path: ${{github.workspace}}/dist/gradient_accumulator-*.whl
          if-no-files-found: error

      - name: Cleanup
        if: always()
        run: |
          rm -rf ${{github.workspace}}/tmp/
